### ISSUE TITLE
MTVR 16.5 Legacy and Boxloader view from passenger

### ISSUE THREAD

**Issue by LeroyTFR** [VurtualRuler98/vurtual_mtvr#2]
Another bug from view under the truck. Only 2 trucks vurtual_mtvr_lhs16_boxloader    and     vurtual_mtvr_lhs16. Other trucks are OK. 
![desktop screenshot 2018 06 02 - 11 39 15 74](https://user-images.githubusercontent.com/44523369/47603645-603fb880-d9ef-11e8-9c1c-81ff243f97c0.png)
![desktop screenshot 2018 06 02 - 11 40 23 70](https://user-images.githubusercontent.com/44523369/47603646-603fb880-d9ef-11e8-91e2-a76e3bda5458.png)

View is from passenger seat. Passenger seat roof hatch is ok.

**Comment by VurtualRuler98** [comment]
I can't seem to replicate this yet, do you have a list of the mods you were running at the time?

**Comment by LeroyTFR** [comment]
RHS mods
Cup_terrains_
Cup_terrains_cwa
Cup_terrains_maps
Ka_comp
Ka_weapons
Louadout_transfer
Nia_wp
Ops_core helmets
Pandur
Pook_camonets
Pook_sam
Projectopfor
Rds_civ (RDS Civillian Pack)
Spec4_gear
Shacktack STUI
Task_force_radio
Zec (ZEC adds a lot of pre-built military objects such as bunkers, bases and outposts)


3den
Ace3
Ace3_compability with RHS
Acex
Achilles
Acr_a3
Acr_a3_rhs
Acr_a3_weapons
Ascz_heads
Baf_a3
Backpack on chest
Cba_a3
CH View Distance
Firewill plane and assets
Metal gear solid accesories
Lav 25 (Chairborne)
JSRS
US Military Mod (80s 90s)
MTVR (RichardsD)
Advance slingloading
Advance towing

**Comment by VurtualRuler98** [comment]
That's a pretty long list of mods. I looked at a few potential conflicts and none of them seemed to cause it, but with that many different mods(and the different orders they could be loaded in) replicating it would be pretty difficult.

You can try using the launcher's mod repair function on my mod and see if that fixes it(corrupt download?), otherwise without knowing what mod specifically causes the bug there's nothing I can really do.

**Comment by LeroyTFR** [comment]
It is okay with new update. Thank you for tips and new update.
